<?php

namespace BackendBundle\Repository;

/**
 * BesoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BesoinRepository extends \Doctrine\ORM\EntityRepository
{
}
