<?php

namespace BackendBundle\Repository;

/**
 * BesoincmdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BesoincmdRepository extends \Doctrine\ORM\EntityRepository
{
}
