<?php

namespace BackendBundle\Repository;

/**
 * MatrielMagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatrielMagRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT m
                FROM BackendBundle:MatrielMag m
                WHERE m.type LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }
    public function findAllmatriels(){
        return $this->getEntityManager()
            ->createQuery(
                "SELECT p
                FROM BackendBundle:MatrielMag p"
            )
            ->getResult();
    }
    public function findEntityByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT m
                FROM BackendBundle:MatrielMag m
                WHERE m.reference LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }
}
