<?php

namespace BackendBundle\Repository;

/**
 * ProdbesoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdbesoinRepository extends \Doctrine\ORM\EntityRepository
{
}
