<?php

namespace BackendBundle\Repository;

/**
 * ProdAchatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdAchatRepository extends \Doctrine\ORM\EntityRepository
{
}
