<?php

namespace BackendBundle\Repository;

/**
 * FournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaffRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllStaffs(){
        return $this->getEntityManager()
            ->createQuery(
                "SELECT p
                FROM BackendBundle:Staff p"
            )
            ->getResult();
    }
    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT m
                FROM BackendBundle:Staff m
                WHERE m.firstname LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }

    public function findNombre(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT m.nb_conj
                FROM BackendBundle:Staff m'
            )
            ->getArrayResult();
    }
}
