<?php

namespace BackendBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use BackendBundle\Entity\User;
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllUsers(){
        return $this->getEntityManager()
            ->createQuery(
                "SELECT p
                FROM BackendBundle:User p
                WHERE p.roles not LIKE 'ROLE_ADMIN' "
            )
            ->getResult();
    }
    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                "SELECT p
                FROM BackendBundle:User p
                WHERE p.username=:str"
            )
            ->setParameter('str', $str)
            ->getResult();
    }
    public function findPassByString($str){
        return $this->getEntityManager()
            ->createQuery(
                "SELECT p
                FROM BackendBundle:User p
                WHERE p.email=:str"
            )
            ->setParameter('str', $str)
            ->getResult();
    }
    public function findUsersByString($str){
        return $this->getEntityManager()
            ->createQuery(
                "SELECT p
                FROM BackendBundle:User p
                WHERE p.roles LIKE ''"
            )
            ->setParameter('str', $str)
            ->getResult();
    }
}
